services:
  app:
    image: node:18-alpine
    container_name: app
    working_dir: /app
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
      - "5555:5555"
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: always
    command: ["sh", "-c", "npx next dev & npx prisma studio", "npx prisma generate"]

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 
      - ./init-replica-set.js:/docker-entrypoint-initdb.d/init-replica-set.js
      - ./mongo_backup:/data/
    command: ["mongod", "--replSet", "rs0"]
    healthcheck:
      test: ["CMD-SHELL", "pgrep mongod || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    

volumes:
  mongo-data:



    