services:

  mongo:
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      
  app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env.production  
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
